#################################
# -e extend_customers_fs

customers_sample_share: 0.01
articles_sample_share: 1
transactions_sample_share: 1

# FEATURE STORE DEV PARAMETERS
fs_n_jobs: -1
customers_max_depth: 3
articles_max_depth: 3

##################
# added new fs date
##################
selected_fs_dates:
  - 2020-09-22
  - 2019-09-22

##################
# added new window
##################
selected_fs_windows:
  - 1Y
  - 6M
  - 2W

selected_agg_primitives:
  - Count 
  - Mean 
  - Sum
  - Max
  - Trend
  - Any
  - TimeSinceLast({'unit':'days'}) 
  - AvgTimeBetween({'unit':'days'})

selected_trans_primitives:
  - TimeSincePrevious({'unit':'days'})
  - NumWords

# which statistics to calculate for "interesting values" defined above
selected_where_primitives:
  - Count


############################################
# INTERESTING VALUES 
# https://featuretools.alteryx.com/en/stable/guides/tuning_dfs.html#Add-"interesting"-values-to-columns

intresting_articles_values_dict: 
  product_type_name:
    - Trousers
    - Dress
    - Sweater
    - T-shirt
    - Top
  index_group_name: 
    - Baby/Children
    - Divided
    - Ladieswear
    - Menswear
    - Sport


interesting_baskets_values_dict:
  if_online_sales_channel: 
    - 1 

interesting_customers_values_dict:
  fashion_news_frequency: 
    - Regularly

############################################
# PRESELECTION OF FEATURES ALGORITHMS PARAMS
# https://featuretools.alteryx.com/en/stable/guides/feature_selection.html
remove_single_value: True

remove_low_information: True

remove_highly_null: True
pct_null_threshold: 0.99

remove_highly_correlated: True
pct_corr_threshold: 0.99



